/* auto-generated by packer */
export namespace Ids {
  export namespace Avatar {
    export namespace Basic {
      export const Happy = 0
      export const Smile = 1
      export const Peaceful = 2
      export const Silly = 3
      export const Agitated = 4
      export const Sad = 5
    }
  }
  export namespace Foreground {
    export namespace Gravity {
      export const Nothing = 6
      export const Left = 7
      export const Up = 8
      export const Right = 9
      export const None = 10
    }
    export namespace Basic {
      export const Gray = 11
      export const Red = 13
      export const Green = 15
      export const Blue = 17
      export const Purple = 19
      export const Yellow = 21
      export const Cyan = 23
    }
    export namespace Metal {
      export const Silver = 25
      export const Gold = 26
      export const Bronze = 27
    }
    export namespace Brick {
      export const Brown = 28
      export const DarkGreen = 29
      export const Green = 30
      export const Purple = 31
    }
    export namespace Misc {
      export const Yellow = 32
    }
    export namespace Gate {
      export const RedKey = 33
      export const RedGateOff = 34
      export const RedGateOn = 35
      export const InverseRedGateOff = 36
      export const InverseRedGateOn = 37
      export const GreenKey = 38
      export const GreenGateOff = 39
      export const GreenGateOn = 40
      export const InverseGreenGateOff = 41
      export const InverseGreenGateOn = 42
      export const BlueKey = 43
      export const BlueGateOff = 44
      export const BlueGateOn = 45
      export const InverseBlueGateOff = 46
      export const InverseBlueGateOn = 47
    }
    export namespace Coin {
      export const YellowCoin = 51
      export const YellowCoinShadow = 52
      export const BlueCoin = 53
      export const BlueCoinShadow = 54
    }
    export namespace CoinGate {
      export const YellowOff = 55
      export const YellowOn = 56
      export const BlueOff = 57
      export const BlueOn = 58
      export const InverseYellowOff = 59
      export const InverseYellowOn = 60
      export const InverseBlueOff = 61
      export const InverseBlueOn = 62
    }
    export namespace Vanish {
      export const GreenOff = 63
      export const GreenOn = 64
    }
    export namespace Portal {
      export const Cyan = 65
    }
    export namespace Sign {
      export const Brown = 66
    }
    export namespace BoostedGravity {
      export const Up = 67
      export const Right = 68
      export const Down = 69
      export const Left = 70
    }
  }
  export namespace Background {
    export namespace Basic {
      export const Gray = 12
      export const Red = 14
      export const Green = 16
      export const Blue = 18
      export const Purple = 20
      export const Yellow = 22
      export const Cyan = 24
    }
  }
  export namespace Decoration {
    export namespace RandomTest {
      export const FireHydrant = 48
      export const RedGlass = 49
      export const TrafficCone = 50
    }
  }
  export namespace Aura {
    export const Aura = 71
  }
}